# 一、ndarray
## 1.ndarray的特性
多维性

In [3]:
import numpy as np

In [11]:
arr = np.array(5)  #创建了一个0维的ndarray数组
print(arr)
print(f"维度为：{arr.ndim}")
print('arr的维度', arr.ndim)

5
维度为：0
arr的维度 0


In [13]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(f"维度为：{arr.ndim}")

[1 2 3 4]
维度为：1


In [14]:
arr = np.array([ [1, 2, 3, 4], [5, 6, 7, 8] ])
print(arr)
print(f"维度为：{arr.ndim}")

[[1 2 3 4]
 [5 6 7 8]]
维度为：2


#同质性

In [16]:
arr = np.array([1, 'a'])  #不同的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'a']


In [18]:
arr = np.array([1, 2.5])  #不同的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.5]


2.ndarray属性

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的类型：', arr.dtype)
print('元素的转置：', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


3. ndarray的创建

In [34]:
#基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64) #里面实际传入的就是一个列表
print(arr) #无逗号

[4 5 6]


In [38]:
arr1 = np.copy(arr)  #复制，arr1元素跟原始的数组相同，但不是一个数组了。不是指向同一块内存空间
arr1[0] = 100
print(arr)
print(arr1)

[4 5 6]
[100   5   6]


In [42]:
#预定义形状
#全0 全1 未初始化 固定值
#全0
#arr = np.zeros((2, 3))  #默认是double，若想指定为int:
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [45]:
arr = np.zeros(10,) #一维
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [53]:
#未初始化
arr10 = np.empty((2, 3))
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr = np.full((3, 4), 2025) #第二个参数是要填充的数值
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [9]:
arr1 = np.zeros_like(arr)  #首先，打印的全是0，其次，形状像arr，arr是3行4列的
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
#等差数列
arr = np.arange(2, 11, 2)  #包头不包尾
print(arr)

[ 2  4  6  8 10]


In [16]:
#等间隔的数列
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
#对数间隔数列
arr = np.logspace(0, 10, 25, base=2)  #25是份数
print(arr)

[1.00000000e+00 1.33483985e+00 1.78179744e+00 2.37841423e+00
 3.17480210e+00 4.23785238e+00 5.65685425e+00 7.55099450e+00
 1.00793684e+01 1.34543426e+01 1.79593928e+01 2.39729132e+01
 3.20000000e+01 4.27148753e+01 5.70175180e+01 7.61092554e+01
 1.01593667e+02 1.35611276e+02 1.81019336e+02 2.41631824e+02
 3.22539789e+02 4.30538965e+02 5.74700569e+02 7.67133223e+02
 1.02400000e+03]


In [23]:
#特殊矩阵
#单位矩阵:主对角线上的数字为1， 其他的数字为0
arr = np.eye(3, 4, dtype=int) #无小括号
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [27]:
#对角矩阵:主对角线上 非0，其他数字为0
arr = np.diag([5,1,2,3])  #主对角线上的数字
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [33]:
#随机数组的生成
#生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3) #形状
print(arr)

[[0.09268675 0.20769149 0.57037272]
 [0.92232974 0.81775374 0.5918853 ]]


In [35]:
#生成指定范围区间的随机浮点数的数组
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[4.89814938 3.11872023 3.31936811]
 [3.68079551 4.67712025 5.2318884 ]]


In [37]:
#生成指定范围区间的随机整数的数组
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[ 6 27 10]
 [ 5 24 20]]


In [40]:
#生成随机数列 （正态分布）
#两边小，中间的概率大
arr = np.random.randn(2, 3)
print(arr)

[[ 0.7480949   0.6555485  -0.86360014]
 [ 0.01743134  1.7750584  -0.69330777]]


In [48]:
#设置随机种子
np.random.seed(20) #如果不设置种子，则每次运行结果不一样
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


4. ndarray的数据类型
布尔类型 bool
整数类型 int uint
浮点数 float
复数 complex


In [50]:
arr = np.array([1, 0, 1, 0], dtype='bool')
print(arr)

[ True False  True False]


In [57]:
arr = np.array([1, 0, 1, 0], dtype='int')
print(arr)

[1 0 1 0]


5.索引与切片

In [65]:
#一维数组的索引与切片
arr = np.random.randint(1, 100, 20) #最小值1，最大值99，一共生成20个这样的数
print(arr)
print(arr[0])
print(arr[:]) #获取全部的数据
print(arr[2:]) #从下标为2开始

[66 83 52 13 37 42 75 97 96 86 32 68 77 43  3 40 97 87 80  8]
66
[66 83 52 13 37 42 75 97 96 86 32 68 77 43  3 40 97 87 80  8]
[52 13 37 42 75 97 96 86 32 68 77 43  3 40 97 87 80  8]


In [70]:
print(arr[2:6]) #包左不包右
print(arr[arr>10]) #打印全部大于10的元素(布尔索引)
print(arr[(arr > 10) & (arr < 50)])  #记得加括号

[52 13 37 42]
[66 83 52 13 37 42 75 97 96 86 32 68 77 43 40 97 87 80]
[13 37 42 32 43 40]


In [72]:
#二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[67 36 88 50 75 28 95 51]
 [ 2 22  6  7 42 69 83 11]
 [65  5 76 16 55 12  5 23]
 [ 7 60 45 74 12 19 53 65]]


In [82]:
print(arr[1][0])
print(arr[:,:]) #原样输出
#print(arr[1,:]) #输出下标为1的一整行
print(arr[1, 2:5])


2
[[67 36 88 50 75 28 95 51]
 [ 2 22  6  7 42 69 83 11]
 [65  5 76 16 55 12  5 23]
 [ 7 60 45 74 12 19 53 65]]
[ 6  7 42]


#要第一行，大于30的元素
print(arr[0] [arr[0] > 30])

In [91]:
#要第一行，输出88 - 75
print(arr[0, 2:5])

[88 50 75]


5.ndarray运算

In [96]:
#算数的运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [99]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a + 3) #数组每个元素都+3

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [101]:
#广播机制 （互相的行与列，能变过去就行）
a = np.array([1, 2, 3]) #1*3
b = np.array([[4], [5], [6]]) #3*1
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [103]:
#矩阵的运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b) #矩阵乘法

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


2.3 numpy中的常用函数
1.基本的数学函数

In [106]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [109]:
#计算指数
print(np.exp(1))  #计算e的多少次方

2.718281828459045


In [110]:
#计算自然对数 lnx
print(np.log(2.71))

0.9969486348916096


In [114]:
#计算正弦值、余弦值
print(np.sin(np.pi))

1.2246467991473532e-16


In [116]:
#计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [118]:
#计算a的b次幂
arr = np.array([-1, 1, 2, -3])
print(np.power(arr, 2))  #每个元素都进行2次幂

[1 1 4 9]


In [121]:
#四舍五入
print(np.round([3.2, 4.5, 9.6])) #4.5-->4; 4.51-->5

[ 3.  4. 10.]


In [126]:
#向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7, 100])
print(np.ceil(arr)) #向上取整
print(np.floor(arr)) #向下取整

[  2.  26.  82. 100.]
[  1.  25.  81. 100.]


In [130]:
#监测缺失值
np.isnan([1, np.nan, 3])

array([False,  True, False])

2. 统计函数
求和、计算平均值、计算中位数、标准差、方差
查找最大值、最小值
计算分位数，累计和、累计差

In [132]:
arr = np.random.randint(1, 20, 8)
print(arr)

[ 6 18 16 17  7  7  8 17]


In [139]:
#求和
print(np.sum(arr))
print(np.sum([1,2,3]))
# 计算平均值
print(np.mean(arr))
#计算中位数
print('中位数是：',np.median(arr)) #注意偶数情况

96
6
12.0
中位数是： 12.0


In [141]:
#计算标准差、方差
#1, 2, 3的平均值：2
#(（1-2）^2 + (2-2)^2 + (3-2)^2) / 3 = 0.666
print(np.var([1, 2, 3])) #方差
print(np.std([1, 2, 3])) #标准差

0.6666666666666666
0.816496580927726


In [144]:
#计算最大值、最小值
print(np.max(arr), np.argmax(arr)) #第二个值是下标

18 1


In [147]:
#中位数：median
print(np.percentile(arr, 0))

6.0


In [150]:
#累计和
arr = np.array([1, 2, 3])
print(np.sum(arr)) #之和
print(np.cumsum(arr)) #累计和
print(np.cumprod(arr)) #累积积

6
[1 3 6]
[1 2 6]


#比较函数
比较是否大于、小于、等于
逻辑与、或、非
检查数组中是否有一个True,是否所有的都为True,自定义条件

In [157]:
#是否大于
print(np.greater([3, 4, 5, 6, 7], 4))
print(np.less([3, 4, 5, 6, 7], 5))
print(np.equal([3, 4, 5, 6, 7], 5))


print(np.equal([3, 4, 5],[4, 4, 4])) #对应位置相比

[False False  True  True  True]
[ True  True False False False]
[False False  True False False]
[False  True False]


In [163]:
print(np.logical_and([5,0],[1,1])) #逻辑与
print(np.logical_or([1,0],[2,2])) #逻辑或
print(np.logical_not([1,0])) #逻辑非

[ True False]
[ True  True]
[False  True]


In [169]:
#检查元素是否至少有一个元素为True
print(np.any([0, 1, 0, 0]))
#检查元素是否全部都是true
print(np.all([1, 1]))

True
True


In [174]:
#自定义条件
#print(np.where(条件， 符合条件，不符合条件))
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr>3, arr, 0)) #arr中元素大于3，则从arr中取，否则就是0
print(np.where(arr>3, 1, 0))

[0 0 0 4 5]
[0 0 0 1 1]


In [176]:
score = np.random.randint(50, 101, 20)
print(score)
print(np.where(score < 60, "不及格", "及格"))

[91 83 82 55 79 89 66 97 86 57 61 73 70 83 85 71 94 54 56 68]
['及格' '及格' '及格' '不及格' '及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '及格'
 '及格' '及格' '及格' '不及格' '不及格' '及格']


In [183]:
#排序函数
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
#arr.sort() #返回值是none，改变了原来数组
print(np.sort(arr)) #不改变原数组
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [185]:
#去重函数
print(np.unique(arr)) #去重与排序

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [188]:
#数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
print(arr1 + arr2) #并不能完成拼接
print(np.concatenate((arr1, arr2))) #注意括号

[3 5 7]
[1 2 3 2 3 4]


In [190]:
#数组的分割
print(np.split(arr, 4)) #分成4份（需要能等分）

[array([45, 48, 65, 68, 68]), array([10, 84, 22, 37, 88]), array([71, 89, 89, 13, 59]), array([66, 40, 88, 47, 89])]


In [192]:
#调整数组形状
print(np.reshape(arr, [4, 5])) #4行5列

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


练习：
1.某城市一周的最高气温为：28，30，29，31，32，30，29
计算平均气温，最高气温，最低气温
找出气温超过30度的天数

In [198]:
arr = np.array([28,30,29,31,32,30,29])
count = 0;
avg = np.average(arr)
max = np.max(arr)
min = np.min(arr)
for i in arr:
    if(i > 30): #这里的 for i in arr，i 本身是数组中的元素值
        count = count + 1
print(f"平均气温为:{avg}, \n最高气温为:{max}, \n最低气温为:{min}, \n超过30度的天数:{count}")

#print(len(arr[arr>30]))

平均气温为:29.857142857142858, 
最高气温为:32, 
最低气温为:28, 
超过30度的天数:2


In [207]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print('每列的最大值：', np.max(arr, axis=0))
print('每行的最小值：', np.min(arr, axis=1))
print(np.where(arr% 2==1, -1, arr))


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值： [7 9 7 6]
每行的最小值： [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
